services:
  postgres:
    container_name: postgres
    image: postgres:15
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
      
  redis:
    image: redis:7-alpine
    container_name: redis-bullmq
    ports:
      - "6379:6379"
    restart: unless-stopped

  adonis_app:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./backend:/app:cached
      - /app/node_modules
    working_dir: /app
    ports:
      - "3333:3333"
      - "9229:9229"
    command: node ace serve --watch

volumes:
  postgres_volume:
