FROM node:22.14.0-alpine3.21

WORKDIR /app

# Copia tudo
COPY . .

# Instala TODAS as dependências (incluindo dev)
RUN npm install

# Expõe a porta da API e a porta de debug opcional
EXPOSE 3333 9229

# Comando padrão em modo dev com ts-node e ace
CMD ["node", "ace", "serve", "--watch"]
